CREATE TABLE IF NOT EXISTS user_fcm_tokens (
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      TEXT        NOT NULL UNIQUE,
    device     VARCHAR(20) NOT NULL DEFAULT 'android',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, token)
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS hp         INTEGER NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS max_hp     INTEGER NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS hp_penalty INTEGER NOT NULL DEFAULT 10;